/*
-- Query: SELECT * FROM `tesis-api`.a_completado
LIMIT 0, 1000

-- Date: 2018-12-02 17:38
*/
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (1,1,1,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (2,1,1,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (3,1,1,3);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (4,1,2,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (5,0,3,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (6,1,4,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (7,1,5,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (8,0,6,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (9,1,7,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (10,1,8,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (11,0,9,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (12,1,10,1);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (13,1,2,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (14,1,3,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (15,1,4,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (16,1,5,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (17,1,6,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (18,1,7,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (19,1,8,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (20,1,9,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (21,0,10,2);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (22,1,2,3);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (23,1,3,3);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (24,1,4,3);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (25,1,5,3);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (26,0,6,3);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (27,0,7,3);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (28,0,8,3);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (29,0,9,3);
INSERT INTO `a_completado` (`ID_A_COMPLETADO`,`INDICADOR_COMPLETADO`,`ID_INDICADOR`,`ID_ALUMNO`) VALUES (30,1,10,3);
