/*
-- Query: SELECT * FROM `tesis-api`.alumno
LIMIT 0, 1000

-- Date: 2018-12-02 17:39
*/
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (1,'pedrito','perez','contreras',10,3);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (2,'juanito','sanchez','vasquez',9,3);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (3,'Daniela','Torres','Rojas',10,3);
