/*
-- Query: SELECT * FROM `tesis-api`.alumno
LIMIT 0, 50000

-- Date: 2019-04-09 03:31
*/
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (1,'pedrito','perez','contreras',10,3);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (2,'juanito','sanchez','vasquez',9,3);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (3,'Daniela','Torres','Rojas',10,3);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (4,'Kevin','Arana','Pinto',8,4);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (5,'Gabriel','Arenas','Díaz',9,4);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (6,'Elisa','Asencio','González',8,4);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (7,'Samuel','Jiménez','Álvarez',8,4);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (8,'Cristobal','Barahona','Matus',9,4);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (9,'Jadiel','Barrera','Olguín',8,4);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (10,'Antonia','Contreras','Berríos',8,4);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (11,'Manuel','Sepúlveda','Muñoz',8,4);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (12,'Alaric','Doderos','Espinoza',9,4);
INSERT INTO `alumno` (`ID_ALUMNO`,`NOMBRE_ALUMNO`,`APELLIDO_PATERNO_ALUMNO`,`APELLIDO_MATERNO_ALUMNO`,`EDAD_ALUMNO`,`ID_CURSO`) VALUES (13,'Diego','Martínez','González',9,4);
