/*
-- Query: SELECT * FROM `tesis-api`.curso
LIMIT 0, 50000

-- Date: 2019-04-09 03:31
*/
INSERT INTO `curso` (`ID_CURSO`,`GRADO_CURSO`,`CANTIDAD_ALUMNOS`) VALUES (1,'Cuarto básico',3);
INSERT INTO `curso` (`ID_CURSO`,`GRADO_CURSO`,`CANTIDAD_ALUMNOS`) VALUES (3,'2° Básico',10);
INSERT INTO `curso` (`ID_CURSO`,`GRADO_CURSO`,`CANTIDAD_ALUMNOS`) VALUES (4,'2° Básico',10);
